import Footer from "@/components/Footer";
import { Header } from "@/components/header/Header";
import { Toaster } from "@/components/ui/toaster";
import { getCurrentUser } from "./actions/userActions";
import "./globals.css";

export const metadata = {
  title: "Almeko",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  const currentUser = await getCurrentUser();
  return (
    <html lang="fr" className="h-full">
      <body className="h-full bg-background">
        <div className="flex flex-col">
          <Header currentUser={currentUser} />
          <div className="m-auto w-full flex-1 py-14">{children}</div>
          <Toaster />
        </div>
        <div className="pt-14">
          <Footer currentUser={currentUser} />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
