import { Header } from "@/components/header/Header";
import "./globals.css";
import { getCurrentUser } from "./actions/getCurrentUser";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Almeko",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  const currentUser = await getCurrentUser();
  return (
    <html lang="fr" className="h-full">
      <body className="h-full bg-background">
        <div className="flex flex-col">
          <Header currentUser={currentUser} />
          <div className="m-auto w-full flex-1 py-14">{children}</div>
          <Toaster />
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
