import { Header } from "@/components/Header";
import "./globals.css";
import { getCurrentUser } from "./actions/getCurrentUser";

export const metadata = {
  title: "Almeko",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  const currentUser = await getCurrentUser();
  return (
    <html lang="fr" className="h-full">
      <body className="h-full bg-background">
        <div className="flex flex-col">
          <Header currentUser={currentUser} />
          <div className="container m-auto mt-10 w-full flex-1 py-14">
            {children}
          </div>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
